set(sources
    src/debug/error_data.cpp
    src/linear_algebra/banded_linear_system.cpp
    src/linear_algebra/dense_linear_system.cpp
    src/linear_algebra/generalised_eigenvalue_system.cpp
    src/testing/reporter.cpp
    src/testing/test_result.cpp
    src/testing/test_suite.cpp
    src/utility/command_line_args.cpp
    src/utility/file_system.cpp
    src/utility/logging.cpp
    src/utility/timer.cpp
)
